# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('site', models.CharField(choices=[('FB', 'Facebook'), ('GP', 'Google+'), ('GH', 'GitHub'), ('IG', 'Instagram'), ('LI', 'LinkedIn'), ('PT', 'Pinterest'), ('TW', 'Twitter'), ('YT', 'YouTube')], max_length=2)),
            ],
        ),
    ]
